config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[new create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all # start by defining rules for all users, also not logged ones
    return unless user.present?

    can :manage, [Comment, Post], author_id: user.id # if the user is logged in can manage it's own posts and comments
    return unless user.admin?

    can :manage, :all # finally we give all remaining permissions only to the admins
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes
  has_many :comments
  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  load_and_authorize_resource
  skip_before_action :verify_authenticity_token

  def index
    @post = Post.find(params[:post_id])
    render json: { success: true, data: { comments: @post.comments } }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], author_id: @post.author_id)

    if @comment.save
      render json: { success: true, data: { comment: @comment } }, status: :created
    else
      render json: { success: false, error: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order('created_at')
    render json: { success: true, data: { posts: @posts } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # prevent users to perfrom action without authentication
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :photo, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :bio, :photo, :password, :current_password) }
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
    def new
        @comment = Comment.new
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.author_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: 'An error has occurred while creating the comment'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comments_counter!)
    @comment.destroy!
    redirect_to user_post_path(id: @post.id), notice: 'Comment successfully deleted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author_id: current_user.id, post_id: @post.id)

    if @like.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: 'An error has occurred while creating the like'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_path(id: @post.author_id)
    else
      render :new, alert: 'An error has occurred while creating the post'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:posts_counter!)
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="container">
    <h1>Add a new comment</h1>
    <%= form_with model: @comment, url: user_post_comments_path do |c| %>
        <%= c.label :text %>
        <%= c.text_area :text, cols: 30, rows: 10 %> <br>
        <%= c.submit "Submit", class: "btn" %>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>List of all posts for <%= @user.name %></h1>

<section class="container">
    <div class="card">
        <div class="img">
            <img src=<%= @user.photo %> alt="user photo" width="100%" height="100%">
        </div>
        <div class="content">
            <h2><%= @user.name %></h2>
            <p>Number of post: <%= @user.posts_counter %></p>
        </div>
    </div>
</section>
<section class="container">
    <ul>
        <% @posts.each do |post| %>
            <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
                <li class="posts">
                    <div class="post">
                        <h3><%= post.title %></h3>
                        <p><%= post.text %></p>
                        <div class="counter">
                            <span>Comments: <%= post.comments_counter %>, </span>
                            <span>Likes: <%= post.likes_counter %> </span>
                        </div>
                    </div>
                    <div class="comment">
                        <% post.recent_comments.includes(:author).each do |comment| %>
                            <p><%= comment.author.name %>: <%= comment.text %></p>
                        <% end %> 
                    </div>
                </li>
            <% end %>
        <% end %>
    </ul>
    <%= link_to "Add a post", new_user_post_path(user_id: @user.id), class: "btn" %>
    <button class="btn pagination">Pagination</button>
</section>

app/views/posts/new.html.erb
<section class="container">
    <h1>Add a new post</h1>
    <%= form_with model: @post, url: user_posts_path do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :text %> 
        <%= f.text_area :text, cols: 30, rows: 10 %> <br>
        <%= f.submit "Submit", class: "btn" %>
    <% end %>
</section>

app/views/posts/show.html.erb
<h1>Welcome to <%= @post.author.name %>'s post</h1>

<section class="container">
    <div class="post">
        <h3><%= @post.title %> by <%= @post.author.name %></h3>
        <div class="counter">
            <span>Comments: <%= @post.comments_counter %>, </span>
            <span>Likes: <%= @post.likes_counter %> </span>
        </div>
        <p><%= @post.text %></p>
        <% if can?(:destroy, @post) %>
            <%= button_to 'Delete', user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "del-btn" %>
        <% end %>
    </div>
    <div class="comment">
        <% @post.comments.includes(:author).includes(:post).each do |comment| %>
            <p><%= comment.author.name %>: <%= comment.text %></p>
            <% if can?(:destroy, @comment) %>
                <%= button_to 'Delete', user_post_comment_path(user_id: @comment.author_id, post_id: @comment.post_id, id: @comment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
            <% end %>
        <% end  %>
    </div>
    <%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id), class: "btn" %>
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |f| %>
        <%= f.submit "Like", class: "btn like" %>
    <% end %>
</section>

app/views/users/_user.html.erb
<!-- _user.html.erb -->
<%= link_to user do %>
    <li class="card">
        <div class="img">
          <img src="<%= user.photo %>" alt="user photo" width="100%" height="100%">
        </div>
        <div class="content">
          <h2><%= user.name %></h2>
          <p>Number of posts: <%= user.posts_counter %></p>
        </div>
    </li>
<% end %>

app/views/users/index.html.erb
<h1>Welcome to Users page</h1>

<div class="container">
    <ul>
         <%= render partial: 'user', collection: @users %>
    </ul>
</div>

app/views/users/show.html.erb
<section class="container">
    <div class="card">
        <div class="img">
            <img src=<%= @user.photo %> alt="user photo" width="100%" height="100%">
        </div>
        <div class="content">
            <h2><%= @user.name %></h2>
            <p>Number of post: <%= @user.posts_counter %></p>
        </div>
    </div>
    <div class="bio">
        <h3>Bio</h3>
        <p><%= @user.bio %></p>
    </div>
</section>
<section class="container">
    <h2 class="posts">Posts</h2>
    <ul>
        <% @user.recent_post.each do |post| %>
            <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
                <li class="post">
                    <h3><%= post.title %></h3>
                    <p><%= post.text %></p>
                    <div class="counter">
                        <span>Comments: <%= post.comments_counter %>, </span>
                        <span>Likes: <%= post.likes_counter %> </span>
                    </div>
                </li>
            <% end %>
        <% end %>
    </ul>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
</section>

app/views/users/show.index.erb
<h1>Here is a list of Users for a given id</h1>